-- BigQuery SQL - Create Managed Tables
-- This script creates permanent managed tables from the external tables

-- Create Balance Sheet Managed Table
CREATE OR REPLACE TABLE `{project_id}.{dataset_id}.balance_sheet` AS
SELECT
  CAST(report_date AS DATE) AS report_date,
  ticker,
  Treasury_Shares_Number,
  Ordinary_Shares_Number,
  Share_Issued,
  Net_Debt,
  Total_Debt,
  Tangible_Book_Value,
  Invested_Capital,
  Working_Capital,
  Net_Tangible_Assets,
  Capital_Lease_Obligations,
  Common_Stock_Equity,
  Total_Capitalization,
  Total_Equity_Gross_Minority_Interest,
  Stockholders_Equity,
  Gains_Losses_Not_Affecting_Retained_Earnings,
  Other_Equity_Adjustments,
  Retained_Earnings,
  Capital_Stock,
  Common_Stock,
  Total_Liabilities_Net_Minority_Interest,
  Total_Non_Current_Liabilities_Net_Minority_Interest,
  Other_Non_Current_Liabilities,
  Tradeand_Other_Payables_Non_Current,
  Long_Term_Debt_And_Capital_Lease_Obligation,
  Long_Term_Capital_Lease_Obligation,
  Long_Term_Debt,
  Current_Liabilities,
  Other_Current_Liabilities,
  Current_Deferred_Liabilities,
  Current_Deferred_Revenue,
  Current_Debt_And_Capital_Lease_Obligation,
  Current_Capital_Lease_Obligation,
  Current_Debt,
  Other_Current_Borrowings,
  Commercial_Paper,
  Payables_And_Accrued_Expenses,
  Current_Accrued_Expenses,
  Payables,
  Total_Tax_Payable,
  Income_Tax_Payable,
  Accounts_Payable,
  Total_Assets,
  Total_Non_Current_Assets,
  Other_Non_Current_Assets,
  Non_Current_Deferred_Assets,
  Non_Current_Deferred_Taxes_Assets,
  Investments_And_Advances,
  Other_Investments,
  Investmentin_Financial_Assets,
  Available_For_Sale_Securities,
  Net_PPE,
  Accumulated_Depreciation,
  Gross_PPE,
  Leases,
  Other_Properties,
  Machinery_Furniture_Equipment,
  Land_And_Improvements,
  Properties,
  Current_Assets,
  Other_Current_Assets,
  Inventory,
  Receivables,
  Other_Receivables,
  Accounts_Receivable,
  Cash_Cash_Equivalents_And_Short_Term_Investments,
  Other_Short_Term_Investments,
  Cash_And_Cash_Equivalents,
  Cash_Equivalents,
  Cash_Financial,
  Other_Intangible_Assets,
  Finished_Goods,
  Goodwill_And_Other_Intangible_Assets,
  Goodwill,
  Long_Term_Equity_Investment,
  Allowance_For_Doubtful_Accounts_Receivable,
  Pensionand_Other_Post_Retirement_Benefit_Plans_Current,
  Buildings_And_Improvements,
  Hedging_Assets_Current,
  Non_Current_Deferred_Taxes_Liabilities,
  Raw_Materials,
  Non_Current_Deferred_Revenue,
  Gross_Accounts_Receivable,
  Work_In_Process,
  Non_Current_Deferred_Liabilities,
  Financial_Assets,
  CURRENT_TIMESTAMP() AS loaded_at
FROM `{project_id}.{dataset_id}.balance_sheet_external`;

-- Create Income Statement Managed Table
CREATE OR REPLACE TABLE `{project_id}.{dataset_id}.income_statement` AS
SELECT
  CAST(report_date AS DATE) AS report_date,
  ticker,
  Tax_Effect_Of_Unusual_Items,
  Tax_Rate_For_Calcs,
  Normalized_EBITDA,
  Net_Income_From_Continuing_Operation_Net_Minority_Interest,
  Reconciled_Depreciation,
  Reconciled_Cost_Of_Revenue,
  EBITDA,
  EBIT,
  Net_Interest_Income,
  Interest_Expense,
  Interest_Income,
  Normalized_Income,
  Net_Income_From_Continuing_And_Discontinued_Operation,
  Total_Expenses,
  Total_Operating_Income_As_Reported,
  Diluted_Average_Shares,
  Basic_Average_Shares,
  Diluted_EPS,
  Basic_EPS,
  Diluted_NI_Availto_Com_Stockholders,
  Net_Income_Common_Stockholders,
  Net_Income,
  Net_Income_Including_Noncontrolling_Interests,
  Net_Income_Continuous_Operations,
  Tax_Provision,
  Pretax_Income,
  Other_Income_Expense,
  Other_Non_Operating_Income_Expenses,
  Net_Non_Operating_Interest_Income_Expense,
  Interest_Expense_Non_Operating,
  Interest_Income_Non_Operating,
  Operating_Income,
  Operating_Expense,
  Research_And_Development,
  Selling_General_And_Administration,
  Gross_Profit,
  Cost_Of_Revenue,
  Total_Revenue,
  Operating_Revenue,
  Total_Unusual_Items_Excluding_Goodwill,
  Write_Off,
  Total_Unusual_Items,
  Gain_On_Sale_Of_Security,
  Other_Gand_A,
  General_And_Administrative_Expense,
  Special_Income_Charges,
  Selling_And_Marketing_Expense,
  CURRENT_TIMESTAMP() AS loaded_at
FROM `{project_id}.{dataset_id}.income_statement_external`;

-- Create Company Info Managed Table
CREATE OR REPLACE TABLE `{project_id}.{dataset_id}.company_info` AS
SELECT
  CAST(report_date AS DATE) AS report_date,
  ticker,
  displayName as company,
  address1 as address,
  city,
  state,
  zip,
  country,
  industry,
  sector,
  longBusinessSummary,
  fullTimeEmployees,
  marketCap,
  enterpriseValue,
  profitMargins,
  sharesOutstanding,
  totalRevenue,
  debtToEquity,
  returnOnAssets,
  returnOnEquity,
  grossProfits,
  freeCashflow,
  operatingCashflow,
  revenueGrowth,
  ebitda,
  totalDebt,
  currentRatio,
  quickRatio,
  CURRENT_TIMESTAMP() AS loaded_at
FROM `{project_id}.{dataset_id}.company_info_external`;

-- Create Cash Flow Statement Managed Table
CREATE OR REPLACE TABLE `{project_id}.{dataset_id}.cash_flow_statement` AS
SELECT
  CAST(report_date AS DATE) AS report_date,
  ticker,
  * EXCEPT(report_date, ticker),
  CURRENT_TIMESTAMP() AS loaded_at
FROM `{project_id}.{dataset_id}.cash_flow_statement_external`;
